name: Format
on: push
permissions:
  contents: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sort macro definitions
        run: |
          sort -o macros/conferences.bib macros/conferences.bib
          sort -o macros/journals.bib macros/journals.bib
      - name: Format publications
        run: |
          sudo apt install -y bibtool
          bibtool -f "%1n(author)%d(year)%2W(title)" -s -R -r bibtool.rsc -i publications.bib -o publications.bib
          bibtool -f "%1n(author)%d(year)%2W(title)" -s -R -r bibtool.rsc -i publications.bib macros/conferences.bib macros/journals.bib -o publications_expanded.bib
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -am "Formatting" || exit 0
          git push
